version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm ci

  build:
    commands:
      - echo Building the application
      - npm run build
      - echo Preparing deployment package
      - mkdir -p deployment
      - cp -R dist/* deployment/
      - cp appspec.yaml deployment/

  post_build:
    commands:
      - echo Creating deployment artifacts
      - zip -r deployment.zip deployment

artifacts:
  files:
    - deployment.zip
  name: react-vite-deployment-$(date +%Y-%m-%d)

cache:
  paths:
    - "node_modules/**/*"
