version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies
      - npm ci

  build:
    commands:
      - echo Building the application
      - npm run build

artifacts:
  files:
    - "**/*"
  base-directory: dist
  discard-paths: no

cache:
  paths:
    - "node_modules/**/*"
